<Project>
  <PropertyGroup>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Authors>Bradley Ruga</Authors>
    <Copyright>Copyright © Bradley Ruga $([System.DateTime]::Now.Year)</Copyright>
    <RepositoryUrl>https://github.com/bradruga/nxgrid</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
  </PropertyGroup>
</Project>
